"""
Security Asset Inventory Engine for E2EE AI Chatbot.
Identifies and characterizes critical protected assets with CIA requirements and primary STRIDE threats.
"""

from typing import List, Dict, Any


ASSETS_DATA = [
    {
        "asset": "User Identity",
        "description": "Long-term public/private key identities, username/credentials, device identifiers, and cryptographic fingerprints.",
        "confidentiality": "High",
        "confidentiality_desc": "Unauthorized exposure permits tracking, profiling, and targeted social engineering attacks.",
        "integrity": "Critical",
        "integrity_desc": "Tampering with public keys or device identifiers allows man-in-the-middle key substitution.",
        "availability": "Moderate",
        "availability_desc": "Identity resolution failure prevents session authentication and chat connectivity.",
        "primary_threats": [
            {"id": "THR-001", "name": "Client Identity Impersonation"},
            {"id": "THR-017", "name": "JWT Algorithm Confusion & Role Escalation"}
        ]
    },
    {
        "asset": "Chat Messages",
        "description": "Cleartext conversational history, messages in transit, and client-side message archives.",
        "confidentiality": "Critical",
        "confidentiality_desc": "Core privacy objective of E2EE; cleartext disclosure violates DPDP, GDPR, and user confidentiality.",
        "integrity": "High",
        "integrity_desc": "Message tampering distorts user statements and can inject adversarial commands.",
        "availability": "High",
        "availability_desc": "Message loss or dropped packets disrupts real-time conversational workflow.",
        "primary_threats": [
            {"id": "THR-005", "name": "Encrypted Message Envelope Header Modification"},
            {"id": "THR-010", "name": "Traffic Analysis & Message Size Profiling"}
        ]
    },
    {
        "asset": "Encryption Keys",
        "description": "Ephemeral ECDH public/private key pairs, root keys, chain keys, and symmetric message ratchet keys.",
        "confidentiality": "Critical",
        "confidentiality_desc": "Exposure of root or ratchet keys compromises past (without forward secrecy) or current conversations.",
        "integrity": "Critical",
        "integrity_desc": "Altering key negotiation parameters (e.g., Diffie-Hellman parameters) forces weak shared keys.",
        "availability": "High",
        "availability_desc": "Key desynchronization halts end-to-end decryption between client and AI enclave.",
        "primary_threats": [
            {"id": "THR-004", "name": "Ephemeral Key Exchange Manipulation"},
            {"id": "THR-011", "name": "Client-Side Ephemeral Key Memory Extraction"}
        ]
    },
    {
        "asset": "Authentication Tokens",
        "description": "Signed RS256/EdDSA JWT tokens, refresh tokens, and temporary session bearer tickets.",
        "confidentiality": "High",
        "confidentiality_desc": "Stolen bearer tokens allow unauthorized API calls within their validity lifetime.",
        "integrity": "Critical",
        "integrity_desc": "Forged or tampered token claims allow horizontal/vertical privilege escalation.",
        "availability": "Moderate",
        "availability_desc": "Token service failure blocks user session renewal and handshake completion.",
        "primary_threats": [
            {"id": "THR-001", "name": "Client Identity Impersonation"},
            {"id": "THR-017", "name": "JWT Algorithm Confusion & Role Escalation"}
        ]
    },
    {
        "asset": "AI Prompts",
        "description": "User queries, system instructions, context windows, and few-shot examples submitted for inference.",
        "confidentiality": "Critical",
        "confidentiality_desc": "Prompts contain proprietary enterprise data, personal inquiries, and intellectual property.",
        "integrity": "Critical",
        "integrity_desc": "Adversarial prompt injection modifies model behavior, triggering rogue actions or data leakage.",
        "availability": "High",
        "availability_desc": "Exhaustion attacks on prompt processing queue deny inference access to other users.",
        "primary_threats": [
            {"id": "THR-006", "name": "Indirect Prompt Injection & Context Manipulation"},
            {"id": "THR-014", "name": "Algorithmic Complexity & Token Expansion Attack"}
        ]
    },
    {
        "asset": "AI Responses",
        "description": "Synthesized output tokens generated by the LLM core prior to and during client re-encryption.",
        "confidentiality": "Critical",
        "confidentiality_desc": "Generated output may contain sensitive analysis, confidential answers, or internal reasoning traces.",
        "integrity": "High",
        "integrity_desc": "Response tampering can fabricate fraudulent advice or inject malicious script into chat clients.",
        "availability": "High",
        "availability_desc": "Generation timeouts or dropped response streams prevent users from receiving answers.",
        "primary_threats": [
            {"id": "THR-012", "name": "Cross-Session AI KV Cache & Memory Leakage"},
            {"id": "THR-014", "name": "Algorithmic Complexity & Token Expansion Attack"}
        ]
    },
    {
        "asset": "Session Information",
        "description": "Active connection states, client sequence counters, routing tags, and transient websocket connections.",
        "confidentiality": "Moderate",
        "confidentiality_desc": "Session metadata reveals communication timing and user presence to network observers.",
        "integrity": "High",
        "integrity_desc": "Desynchronizing sequence counters causes replay protection to reject genuine subsequent packets.",
        "availability": "High",
        "availability_desc": "State exhaustion on gateway/relay closes active user sessions prematurely.",
        "primary_threats": [
            {"id": "THR-013", "name": "Asymmetric TLS & Handshake Exhaustion Attack"},
            {"id": "THR-015", "name": "Relay Buffer Overfill with Bogus Ciphertext Blobs"}
        ]
    },
    {
        "asset": "Audit Records",
        "description": "Security logs, administrative access trails, authentication histories, and rate-limiting triggers.",
        "confidentiality": "Moderate",
        "confidentiality_desc": "Logs must redact cleartext prompt data to comply with privacy policies.",
        "integrity": "Critical",
        "integrity_desc": "Tampering with logs erases evidence of intrusion and subverts regulatory compliance.",
        "availability": "High",
        "availability_desc": "Loss of audit pipelines impairs incident detection and live security monitoring.",
        "primary_threats": [
            {"id": "THR-007", "name": "Audit Trail Erasure by Privileged Operator"},
            {"id": "THR-009", "name": "Unsigned Administrative Policy Override"}
        ]
    },
    {
        "asset": "System Configuration",
        "description": "TLS cipher suites, firewall policies, model safety guardrail rules, and API routing manifests.",
        "confidentiality": "High",
        "confidentiality_desc": "Exposing internal security rules provides attackers blueprints for bypass techniques.",
        "integrity": "Critical",
        "integrity_desc": "Modifying system configs can downgrade cryptographic protocols or disable guardrails.",
        "availability": "High",
        "availability_desc": "Corrupt configuration files crash gateway and inference workers.",
        "primary_threats": [
            {"id": "THR-009", "name": "Unsigned Administrative Policy Override"},
            {"id": "THR-016", "name": "Insecure Direct Object Reference (IDOR) on Admin API"}
        ]
    }
]


class AssetInventoryEngine:
    """
    Provides query methods for the protected security asset inventory.
    """

    @staticmethod
    def get_all_assets() -> List[Dict[str, Any]]:
        """Returns the full list of protected security assets."""
        return list(ASSETS_DATA)

    @staticmethod
    def get_asset_by_name(name: str) -> Dict[str, Any]:
        """Returns asset specification by name."""
        for a in ASSETS_DATA:
            if a["asset"].lower() == name.lower():
                return dict(a)
        return {}

    @staticmethod
    def get_cia_summary() -> Dict[str, Any]:
        """Summarizes requirements across Confidentiality, Integrity, and Availability."""
        summary = {
            "critical_confidentiality": [a["asset"] for a in ASSETS_DATA if a["confidentiality"] == "Critical"],
            "critical_integrity": [a["asset"] for a in ASSETS_DATA if a["integrity"] == "Critical"],
            "high_availability": [a["asset"] for a in ASSETS_DATA if a["availability"] == "High"]
        }
        return summary
